version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: scalable
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: scalable
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
volumes:
  db:
    driver: local
