version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: midterms
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
  backend:
    image: ghcr.io/fceaurrutia/midterms-backend/midterms-backend:latest
    ports:
      - '3005:3005'
volumes:
  db:
    driver: local
